/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame2.java
 *
 * Created on May 24, 2016, 12:21:41 AM
 */

/**
 *
 * @author USER
 */
import java.sql.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class NewJFrame2 extends javax.swing.JFrame {

    /** Creates new form NewJFrame2 */
    public NewJFrame2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        B1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        T1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        TF1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TF5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        TF13 = new javax.swing.JTextField();
        TF4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TF10 = new javax.swing.JTextField();
        TF3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TF2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        TF12 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TF8 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        JCB2 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        TF6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TF7 = new javax.swing.JTextField();
        TF9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        RB1 = new javax.swing.JRadioButton();
        RB2 = new javax.swing.JRadioButton();
        JCB1 = new javax.swing.JComboBox();
        B4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        CB1 = new javax.swing.JCheckBox();
        b1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        TF11 = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("AR ESSENCE", 1, 24));
        jLabel1.setText("sell");
        jLabel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel1FocusGained(evt);
            }
        });

        jList1.setModel(new DefaultListModel());
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jList1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jList1FocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        B1.setText("Get Details");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        T1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order code", "mid", "mname", "pid", "pname", "size/capacity", "qty", "price", "total", "selling date"
            }
        ));
        jScrollPane2.setViewportView(T1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Member details"));

        TF1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TF1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TF1FocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Aharoni", 0, 14));
        jLabel7.setText("Member name");

        TF5.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Aharoni", 0, 14));
        jLabel3.setText("Enter memberid");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(TF5, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Product Details"));

        TF13.setEditable(false);
        TF13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF13ActionPerformed(evt);
            }
        });

        TF4.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Aharoni", 0, 14));
        jLabel6.setText("Mrp");

        TF10.setEditable(false);

        TF3.setEditable(false);
        TF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF3ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Aharoni", 0, 14));
        jLabel13.setText("Quantity in stock");

        jLabel4.setFont(new java.awt.Font("Aharoni", 0, 14));
        jLabel4.setText("Product id");

        jLabel16.setFont(new java.awt.Font("Aharoni", 0, 14));
        jLabel16.setText("Size/capacity");

        jLabel5.setFont(new java.awt.Font("Aharoni", 0, 14));
        jLabel5.setText("Product name");

        TF2.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jLabel6))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TF2, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addComponent(TF13, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addComponent(TF4, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addComponent(TF10, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                    .addComponent(TF3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(TF13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TF10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Aharoni", 0, 14));
        jLabel15.setText("Order code");

        TF12.setEditable(false);
        TF12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF12ActionPerformed(evt);
            }
        });
        TF12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TF12FocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Aharoni", 0, 14));
        jLabel11.setText("Todays date");

        TF8.setEditable(false);
        TF8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TF8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TF8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("order details"));

        JCB2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select discount %", "0", "5", "10", "15", "20", "40" }));
        JCB2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCB2ItemStateChanged(evt);
            }
        });
        JCB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB2ActionPerformed(evt);
            }
        });
        JCB2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JCB2FocusGained(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Aharoni", 0, 14));
        jLabel10.setText("selling price");

        TF6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TF6FocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Aharoni", 0, 14));
        jLabel8.setText("qty");

        jLabel9.setFont(new java.awt.Font("Aharoni", 0, 14));
        jLabel9.setText("discount");

        TF7.setEditable(false);

        TF9.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Aharoni", 0, 14));
        jLabel12.setText("Total");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8)))
                .addGap(67, 67, 67)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TF9)
                    .addComponent(TF6)
                    .addComponent(JCB2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TF7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(TF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Search By"));

        search.add(RB1);
        RB1.setSelected(true);
        RB1.setText("category");
        RB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB1ActionPerformed(evt);
            }
        });

        search.add(RB2);
        RB2.setText("product id");
        RB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RB1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RB2)
                .addGap(8, 8, 8))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RB1)
                    .addComponent(RB2))
                .addContainerGap())
        );

        JCB1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "categories", "Food preservation", "Food preparation", "Bottle", "Tiffin", "serving" }));
        JCB1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCB1ItemStateChanged(evt);
            }
        });
        JCB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB1ActionPerformed(evt);
            }
        });
        JCB1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JCB1FocusGained(evt);
            }
        });

        B4.setText("Remove last order");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        jButton1.setText("Orders Completed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CB1.setText("Confirm Order");
        CB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB1ActionPerformed(evt);
            }
        });
        CB1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CB1FocusLost(evt);
            }
        });

        b1.setText("place order");
        b1.setEnabled(false);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Aharoni", 0, 14));
        jLabel14.setText("Total amount payable");

        TF11.setEditable(false);
        TF11.setText("0");
        TF11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF11ActionPerformed(evt);
            }
        });

        jButton2.setText("Back to home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                    .addComponent(JCB1, javax.swing.GroupLayout.Alignment.LEADING, 0, 191, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(B1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CB1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b1)
                                .addGap(18, 18, 18)
                                .addComponent(B4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jButton1)))
                .addContainerGap(1008, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(JCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B1)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB1)
                    .addComponent(b1)
                    .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TF11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(531, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
void emptyList() {
    DefaultListModel model=(DefaultListModel)jList1.getModel();
    while(model.getSize()>0)
        model.remove(0);
}
    private void JCB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB1ActionPerformed

        emptyList();
        try{
                Class.forName("java.sql.DriverManager");
                Connection con=DriverManager.getConnection("jdbc:mysql://Localhost:3306/tupperware","root","root");
                String category="",sql;
              
               int inde=JCB1.getSelectedIndex();
               switch(inde)
               {case 0:
                   case 1:category="food preservation";
                   break;
                   case 2:category="food preparation";
                    break;
                   case 3:category="bottle"; break;
                   case 4:category="tiffin"; break;

                   case 5:category="serving";break;}
                sql="select concat(pname,'(',size,')') from product where category='"+category+"'"+"order by pid desc";
                Statement st=con.createStatement();
                ResultSet rs=st.executeQuery(sql);
                while(rs.next())
                {
                  String pname[] ={rs.getString("concat(pname,'(',size,')')")};
                 
                 
                   DefaultListModel x=new DefaultListModel();
                x=(DefaultListModel)jList1.getModel();
                for(int i=0;i<pname.length;i++)
                    x.add(i,pname[i]);
                jList1.setModel(x);
                   
                }
                


               
 }

                 catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }


        // TODO add your handling code here:
    }//GEN-LAST:event_JCB1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jList1MouseClicked

    private void JCB1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCB1ItemStateChanged
 TF7.setText("");
                TF9.setText("");
TF6.setText("");

 TF2.setText("");
                TF3.setText("");
TF4.setText("");
TF10.setText("");


        // TODO add your handling code here:
    }//GEN-LAST:event_JCB1ItemStateChanged

    private void jList1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList1FocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_jList1FocusGained

    private void jLabel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel1FocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1FocusGained

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
try

 { 



    
                Class.forName("java.sql.DriverManager");
                Connection con=DriverManager.getConnection("jdbc:mysql://Localhost:3306/tupperware","root","root");


                 if(RB1.isSelected())
                 {  String sql;
                 String pname=(String)jList1.getSelectedValue();
                 TF2.setText(pname);
                sql="select * from product where concat(pname,'(',size,')')='"+pname+"'";
                         Statement st=con.createStatement();
                ResultSet rs=st.executeQuery(sql);
            if(rs.next())
               TF3.setText(rs.getString("pid"));
                TF4.setText(rs.getString("mrp"));
                 TF10.setText(rs.getString("qtyavailable"));
                 TF13.setText(rs.getString("size"));
                 }
                 else if(RB2.isSelected())
                 {
                    int pid=Integer.parseInt(TF3.getText());
                    String sql1;
                    sql1="select * from product where pid="+pid;
                     Statement st1=con.createStatement();
                ResultSet rs1=st1.executeQuery(sql1);
            if(!rs1.next())
            {
               JOptionPane.showMessageDialog(null,"Please enter appropriate value");
            }else
            {
                TF2.setText(rs1.getString("pname"));
                 TF4.setText(rs1.getString("mrp"));
                 TF10.setText(rs1.getString("qtyavailable"));
                 TF13.setText(rs1.getString("size"));

                 }}

            

         


 }
                  catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }

 
        // TODO add your handling code here:
}//GEN-LAST:event_B1ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
 TF2.setText("");
  TF3.setText("");
   TF4.setText("");
   
               TF13.setText("");
                TF6.setText("");
      TF7.setText("");
      TF9.setText("");
       TF10.setText("");



            

         






       






        // TODO add your handling code here:
    }//GEN-LAST:event_jList1ValueChanged

    private void JCB1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JCB1FocusGained
 
       
   
        // TODO add your handling code here:
    }//GEN-LAST:event_JCB1FocusGained

    private void TF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF3ActionPerformed

    private void TF1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF1FocusLost
 try{
                Class.forName("java.sql.DriverManager");
                Connection con=DriverManager.getConnection("jdbc:mysql://Localhost:3306/tupperware","root","root");
                  String mid,sql;
                mid=TF1.getText();
                sql="select * from member where mid="+mid;
                Statement st=con.createStatement();
                ResultSet rs=st.executeQuery(sql);
                if(!rs.next())
                { JOptionPane.showMessageDialog(null,"No such member");
                 TF1.setEditable(true);
                 TF1.setText("");
                }
                else{
                 TF5.setText(rs.getString("name"));
                 TF1.setEditable(false);
                }
                 }

                 catch(Exception e)
            {String p=TF1.getText();
                     if(p.isEmpty()==false)
                JOptionPane.showMessageDialog(null,e.getMessage());
            }


        // TODO add your handling code here:
}//GEN-LAST:event_TF1FocusLost

    private void TF8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF8ActionPerformed

    private void TF12FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF12FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TF12FocusLost

    private void TF13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
float x=Float.parseFloat(TF11.getText());
        JOptionPane.showMessageDialog(null,"Thank You!! \n"+"Your total order is of rs "+x);
        DefaultTableModel model1=(DefaultTableModel) T1.getModel();
                     int rows=model1.getRowCount();
                     if (rows>0)
                     {
                         for(int i=0;i<rows;i++)
                             model1.removeRow(0);
                     }
                     TF1.setEditable(true);
                     TF1.setText("");
                     TF5.setText("");
                     TF3.setText("");
                     TF2.setText("");
                     TF13.setText("");
                     TF4.setText("");
                     TF10.setText("");
                     TF6.setText("");
                     TF7.setText("");
                     TF9.setText("");
                     TF11.setText(""+0);
                    

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
int o=Integer.parseInt(TF12.getText());

        try{
                Class.forName("java.sql.DriverManager");
                Connection con=DriverManager.getConnection("jdbc:mysql://Localhost:3306/tupperware","root","root");
                DefaultTableModel T=(DefaultTableModel)T1.getModel();
                int row=T1.getRowCount();
                 
                 
                 if (row==0)
                 {
                      JOptionPane.showMessageDialog(null,"Please place some orders");
                 }
                 else
                 {
                   Object a=T1.getValueAt(0,0);
 a=T.getValueAt(row-1,0);
 String k=(String)a;
int d=Integer.parseInt(k);


  Object b=T1.getValueAt(0,3);
  b=T.getValueAt(row-1,3);
 String l=(String)b;
int n=Integer.parseInt(l);

String qty="",sql="",sql1="",sql2="";
sql="select * from sales where ordercode="+d;

Statement st=con.createStatement();
ResultSet rs=st.executeQuery(sql);
if(rs.next())
{qty=rs.getString("qty");
int q=Integer.parseInt(qty);

sql2="update product set qtyavailable=qtyavailable+"+q+" where pid="+n;


Statement st2=con.createStatement();
st2.executeUpdate(sql2);
}



sql1="delete from sales where ordercode="+d;
Statement st1=con.createStatement();
st1.executeUpdate(sql1);


Object c=T1.getValueAt(0,8);
 c=T1.getValueAt(row-1,8);
 String z=(String)c;
 float tot=Float.parseFloat(z);
 float total=Float.parseFloat(TF11.getText());
 TF11.setText(""+(total-tot));

 T.removeRow(row-1);




 if(row==0)
{
  TF12.setText(""+o);
}
 else
 {
     TF12.setText(""+(o-1));
 }

    }}










  

            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }


        // TODO add your handling code here:
    }//GEN-LAST:event_B4ActionPerformed

    private void TF12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF12ActionPerformed

    private void RB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB2ActionPerformed

    jLabel4.setText("Enter Product Id");
jList1.setEnabled(false);
JCB1.setEnabled(false);
TF3.setEditable(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_RB2ActionPerformed

    private void RB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB1ActionPerformed
jLabel4.setText("Product Id");
jList1.setEnabled(true);
JCB1.setEnabled(true);
TF3.setEditable(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_RB1ActionPerformed

    private void TF1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF1FocusGained
     try{
                Class.forName("java.sql.DriverManager");
                Connection con=DriverManager.getConnection("jdbc:mysql://Localhost:3306/tupperware","root","root");
                String sql,sql1,oc="";
                sql="select curdate();";
                      Statement st=con.createStatement();
                ResultSet rs=st.executeQuery(sql);
            if(rs.next())
            {TF8.setText(rs.getString("curdate()"));}

 sql1="select ifnull(max(ordercode),0) from sales;";
  Statement st1=con.createStatement();
  ResultSet rs1=st1.executeQuery(sql1);
            if(rs1.next())
            {
            oc=rs1.getString("ifnull(max(ordercode),0)");


            int ordercode=Integer.parseInt(oc);
            TF12.setText(""+(ordercode+1));

 }}
                  catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_TF1FocusGained

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed

        int qt=Integer.parseInt(TF10.getText());
        int qta=Integer.parseInt(TF6.getText());
        int ocode=Integer.parseInt(TF12.getText());
        if(qt>=qta)

        {
            TF10.setText(""+(qt-qta));
            float tot=Float.parseFloat(TF9.getText());
            float amtpay=Float.parseFloat(TF11.getText());

            try{
                Class.forName("java.sql.DriverManager");
                Connection con=DriverManager.getConnection("jdbc:mysql://Localhost:3306/tupperware","root","root");
                String ordercode,size,mid,mname,pid,pname,qty,price,total,sellingdate,sql="",sql1,leftqty="";
                ordercode=TF12.getText();
                mid=TF1.getText();
                mname=TF5.getText();
                pid =TF3.getText();
                pname=TF2.getText();
                qty=TF6.getText();
                price=TF7.getText();
                total=TF9.getText();
                sellingdate=TF8.getText();
                size=TF13.getText();


                TF11.setText(""+(tot+amtpay));



                {Object newRow[]={TF12.getText(),TF1.getText(),TF5.getText(),TF3.getText(),TF2.getText(),size=TF13.getText(),TF6.getText(),TF7.getText(),TF9.getText(),TF8.getText()};
                 DefaultTableModel T=(DefaultTableModel)T1.getModel();
                 T.addRow(newRow);
                }


                sql1="update product set qtyavailable=qtyavailable-"+qty+" where pid="+pid;
                Statement st1=con.createStatement();
                st1.executeUpdate(sql1);

                sql="insert into sales values("+ordercode+","+mid+",'"+mname+"',"+pid+",'"+pname+"','"+size+"',"+qty+","+price+","+total+",'"+sellingdate+"')";
                Statement st=con.createStatement();
                st.executeUpdate(sql);

                JOptionPane.showMessageDialog(null,"order placed");



            }

            catch(Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }} else{
            JOptionPane.showMessageDialog(null,"These many products are not availabe.."+qt+" of these are in stock");
            }



        ocode++;
        TF12.setText(""+ocode);
        b1.setEnabled(false);

        TF2.setText("");
        TF3.setText("");
        TF4.setText("");
        TF13.setText("");
        TF6.setText("");
        TF7.setText("");
        TF9.setText("");
        TF10.setText("");











        // TODO add your handling code here:
}//GEN-LAST:event_b1ActionPerformed

    private void TF11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF11ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_TF11ActionPerformed

    private void CB1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CB1FocusLost
        CB1.setSelected(false);
        // TODO add your handling code here:
}//GEN-LAST:event_CB1FocusLost

    private void CB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB1ActionPerformed
        if(CB1.isSelected())


        {
            String a1=TF1.getText();
            String a2=TF12.getText();
            String a3=TF6.getText();
            String a4=TF7.getText();

            {if(a1.isEmpty()||a2.isEmpty()||a3.isEmpty()||a4.isEmpty()) {
                 b1.setEnabled(false);
                 l3.setText("fill all");
             } else {
                 b1.setEnabled(true);
                 l3.setText("");
             }


            }} else
                b1.setEnabled(false);





        // TODO add your handling code here:
}//GEN-LAST:event_CB1ActionPerformed

    private void TF6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF6FocusLost
        int qtyavailable=Integer.parseInt(TF10.getText());
        int qty=Integer.parseInt(TF6.getText());
        if(qty>qtyavailable) {
            JOptionPane.showMessageDialog(null,"These many products are not availabe.."+qtyavailable+" of these are in stock");
            b1.setEnabled(false);
        } else
            b1.setEnabled(true);


        // TODO add your handling code here:
}//GEN-LAST:event_TF6FocusLost

    private void JCB2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JCB2FocusGained
        b1.setEnabled(false);
        // TODO add your handling code here:
}//GEN-LAST:event_JCB2FocusGained

    private void JCB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB2ActionPerformed
       float dis=0.0f;
        String mrp=(TF4.getText());
        float mr=Float.parseFloat(mrp);
        String disc=(String)JCB2.getSelectedItem();
        int p=JCB2.getSelectedIndex();
        if(p==0) {
            JOptionPane.showMessageDialog(null,"Please select appropriate discount");
        } else
            dis=Float.parseFloat(disc);
        float tot=mr-(mr*dis/100);
        TF7.setText(""+tot);
        int qty=Integer.parseInt(TF6.getText());
        TF9.setText(""+qty*tot);
        b1.setEnabled(false);
        // TODO add your handling code here:
}//GEN-LAST:event_JCB2ActionPerformed

    private void JCB2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCB2ItemStateChanged
       




        // TODO add your handling code here:
}//GEN-LAST:event_JCB2ItemStateChanged

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
  try{
                Class.forName("java.sql.DriverManager");
                Connection con=DriverManager.getConnection("jdbc:mysql://Localhost:3306/tupperware","root","root");
                String sql,sql1,oc="";
                sql="select curdate();";
                      Statement st=con.createStatement();
                ResultSet rs=st.executeQuery(sql);
            if(rs.next())
            {TF8.setText(rs.getString("curdate()"));}

 sql1="select ifnull(max(ordercode),0) from sales;";
  Statement st1=con.createStatement();
  ResultSet rs1=st1.executeQuery(sql1);
            if(rs1.next())
            {
            oc=rs1.getString("ifnull(max(ordercode),0)");


            int ordercode=Integer.parseInt(oc);
            TF12.setText(""+(ordercode+1));

 }}
                  catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  new NewJFrame6().setVisible(true);
  this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B4;
    private javax.swing.JCheckBox CB1;
    private javax.swing.JComboBox JCB1;
    private javax.swing.JComboBox JCB2;
    private javax.swing.JRadioButton RB1;
    private javax.swing.JRadioButton RB2;
    private javax.swing.JTable T1;
    private javax.swing.JTextField TF1;
    private javax.swing.JTextField TF10;
    private javax.swing.JTextField TF11;
    private javax.swing.JTextField TF12;
    private javax.swing.JTextField TF13;
    private javax.swing.JTextField TF2;
    private javax.swing.JTextField TF3;
    private javax.swing.JTextField TF4;
    private javax.swing.JTextField TF5;
    private javax.swing.JTextField TF6;
    private javax.swing.JTextField TF7;
    private javax.swing.JTextField TF8;
    private javax.swing.JTextField TF9;
    private javax.swing.JButton b1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel l3;
    private javax.swing.ButtonGroup search;
    // End of variables declaration//GEN-END:variables

}
