/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame5.java
 *
 * Created on May 25, 2016, 4:07:50 PM
 */

/**
 *
 * @author USER
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class NewJFrame5 extends javax.swing.JFrame {

    /** Creates new form NewJFrame5 */
    public NewJFrame5() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qty = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        TF1 = new javax.swing.JTextField();
        TF2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        T1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        TF3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        TF4 = new javax.swing.JTextField();
        JCB1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        RB1 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("AR JULIAN", 0, 30));
        jLabel1.setText("search everyday sales");

        TF1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TF1FocusGained(evt);
            }
        });

        TF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF2ActionPerformed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        T1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ordercode", "mid", "mname", "pid", "pname", "qty", "price", "total", "selling date"
            }
        ));
        jScrollPane2.setViewportView(T1);

        jLabel4.setFont(new java.awt.Font("Aharoni", 0, 14));
        jLabel4.setText("Enter ordercode of order to be deleted");

        TF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF3ActionPerformed(evt);
            }
        });
        TF3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TF3FocusGained(evt);
            }
        });

        jButton2.setText("delete");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Calculate total sales");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        TF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF4ActionPerformed(evt);
            }
        });

        JCB1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "date", "mid", "date and mid", "all" }));
        JCB1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCB1ItemStateChanged(evt);
            }
        });
        JCB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB1ActionPerformed(evt);
            }
        });
        JCB1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JCB1FocusGained(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Do you want available quantity of product to be updated?"));

        qty.add(jRadioButton2);
        jRadioButton2.setText("no");

        qty.add(RB1);
        RB1.setSelected(true);
        RB1.setText("yes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(RB1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(97, 97, 97))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RB1)
                    .addComponent(jRadioButton2))
                .addContainerGap())
        );

        jButton4.setText("Back to home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Aharoni", 0, 14));
        jLabel5.setText("Search by");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel1)
                .addContainerGap(753, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(JCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)))
                .addGap(258, 258, 258)
                .addComponent(jButton2)
                .addContainerGap(778, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(348, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(28, 28, 28)
                .addComponent(TF4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(696, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TF2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addComponent(TF3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(608, 608, 608))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TF1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(11, 11, 11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(l2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TF2))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(TF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
                Class.forName("java.sql.DriverManager");
                Connection con=DriverManager.getConnection("jdbc:mysql://Localhost:3306/tupperware","root","root");


                String s="select * from sales ";
int d=JCB1.getSelectedIndex();
String b="";
switch(d)
{
case 0: l1.setText("enter date");
String date=TF1.getText();
b="where sellingdate='"+date+"'";
break;

    case 1: int mid=Integer.parseInt(TF1.getText());
    b="where mid="+mid;
    break;


    case 2: int mid1=Integer.parseInt(TF1.getText());
 String date1=TF2.getText();
 b="where mid="+mid1+" and sellingdate='"+date1+"'";
 break;


    case 3:
        
        b="";break;

}



                String sql;
        
                 sql=s+b;
                Statement st=con.createStatement();
                ResultSet rs=st.executeQuery(sql);
                { if(!rs.first())
                {  JOptionPane.showMessageDialog(null,"No orders");
                   
                }
                  else
                  {
                      DefaultTableModel T=(DefaultTableModel)T1.getModel();
                    Object newRow[]={rs.getString("ordercode"),rs.getString("mid"),rs.getString("name"),rs.getString("pid"),rs.getString("pname"),rs.getString("qty"),rs.getString("price"),rs.getString("total"),rs.getString("sellingdate")};
                T.addRow(newRow);
                  }

                 
                while(rs.next())
                 {  DefaultTableModel T=(DefaultTableModel)T1.getModel();
                    Object newRow[]={rs.getString("ordercode"),rs.getString("mid"),rs.getString("name"),rs.getString("pid"),rs.getString("pname"),rs.getString("qty"),rs.getString("price"),rs.getString("total"),rs.getString("sellingdate")};
               

                T.addRow(newRow);
                }
                  jButton1.setEnabled(false);


                 }}

                 catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF3ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_TF3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jButton2.setEnabled(false);
        try{
                Class.forName("java.sql.DriverManager");
                Connection con=DriverManager.getConnection("jdbc:mysql://Localhost:3306/tupperware","root","root");
                String ordercode,sql,sql1,q="",sql2="",pid="";
                ordercode=TF3.getText();

                 DefaultTableModel model=(DefaultTableModel) T1.getModel();
                  sql1="select * from sales where ordercode="+ordercode;

                  if(RB1.isSelected())
                  {  Statement st1=con.createStatement();
                 ResultSet rs=st1.executeQuery(sql1);
                if(!rs.next())
                {
                    JOptionPane.showMessageDialog(this,"Please enter appropriate ordercode");
                    TF3.setText("");
                   return;

                }
                else

                  q=(rs.getString("qty"));
                 int qt=Integer.parseInt(q);
                 pid=(rs.getString("pid"));

                 sql2="update product set qtyavailable=qtyavailable+"+qt+" where pid='"+pid+"'";
                  Statement st2=con.createStatement();
            st2.executeUpdate(sql2);



                
                sql="delete from sales where ordercode="+ordercode;
                Statement st=con.createStatement();
                 st.executeUpdate(sql);
                    

                    
                     int rows=model.getRowCount();
                     if (rows>0)
                     {
                         for(int i=0;i<rows;i++)
                             model.removeRow(0);
                     }
                       jButton1.setEnabled(true);
                       TF3.setText("");
                       JOptionPane.showMessageDialog(null,"the order "+ordercode+" is deleted");
                  }
                  else
                  {
                   sql="delete from sales where ordercode="+ordercode;
                Statement st=con.createStatement();
                 st.executeUpdate(sql);
                    


                     int rows=model.getRowCount();
                     if (rows>0)
                     {
                         for(int i=0;i<rows;i++)
                             model.removeRow(0);
                     }
                       jButton1.setEnabled(true);
                  
                   TF3.setText("");
                   JOptionPane.showMessageDialog(this,"The order "+ordercode+" is deleted");


 }}
     catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TF1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF1FocusGained
DefaultTableModel model=(DefaultTableModel) T1.getModel();
                     int rows=model.getRowCount();
                     if (rows>0)
                     {
                         for(int i=0;i<rows;i++)
                             model.removeRow(0);
                     }
        jButton1.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_TF1FocusGained

    private void TF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 DefaultTableModel model=(DefaultTableModel) T1.getModel();
 int row=T1.getRowCount();
 float j=0.0f;
 int rindex=row;
 int index=0;
 float m=0.0f;
 while(index<rindex)
 {
  Object a=T1.getValueAt(0,7);
 a=T1.getValueAt(index,7);
 String k=(String)a;
 float d=Float.parseFloat(k);
 j=j+d;
 


 index++;




 }TF4.setText(""+j);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void JCB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB1ActionPerformed
        int d=JCB1.getSelectedIndex();
switch(d)
{
case 0: l1.setVisible(true);
    l1.setText("enter date");
TF1.setVisible(true);
TF1.setText("");
 l2.setVisible(false);
 TF2.setVisible(false);
  jButton1.setText("Search");


break;

    case 1: l1.setVisible(true);
    l1.setText("enter memberid");
TF1.setVisible(true);
TF1.setText("");
 l2.setVisible(false);
 TF2.setVisible(false);
  jButton1.setText("Search");

    break;

    case 2: l1.setVisible(true);
     l2.setVisible(true);
    l1.setText("enter memberid");
     l2.setText("enter sellingdate");
TF1.setVisible(true);
TF2.setVisible(true);
TF1.setText("");
TF2.setText("");
 jButton1.setText("Search");
break;

    case 3: jButton1.setText("Search whole sales");
    l1.setVisible(false);
l2.setVisible(false);
TF1.setVisible(false);
TF2.setVisible(false);
    break;

}

DefaultTableModel model=(DefaultTableModel) T1.getModel();
                     int rows=model.getRowCount();
                     if (rows>0)
                     {
                         for(int i=0;i<rows;i++)
                             model.removeRow(0);
                     }
        // TODO add your handling code here:
    }//GEN-LAST:event_JCB1ActionPerformed

    private void JCB1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCB1ItemStateChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_JCB1ItemStateChanged

    private void JCB1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JCB1FocusGained
TF4.setText("");
        l1.setVisible(false);
l2.setVisible(false);
TF1.setVisible(false);
TF2.setVisible(false);
jButton1.setEnabled(true);
DefaultTableModel model=(DefaultTableModel) T1.getModel();
 int rows=model.getRowCount();
                     if (rows>0)
                     {
                         for(int i=0;i<rows;i++)
                             model.removeRow(0);
                     }
        // TODO add your handling code here:
    }//GEN-LAST:event_JCB1FocusGained

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new NewJFrame6().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

    private void TF3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF3FocusGained
jButton2.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_TF3FocusGained

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JCB1;
    private javax.swing.JRadioButton RB1;
    private javax.swing.JTable T1;
    private javax.swing.JTextField TF1;
    private javax.swing.JTextField TF2;
    private javax.swing.JTextField TF3;
    private javax.swing.JTextField TF4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.ButtonGroup qty;
    // End of variables declaration//GEN-END:variables

}
